# Generated by Django 3.2.4 on 2021-06-08 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210608_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='info',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
